---
title: "SINET_somatic"
author: "Stephen Henderson"
date: "7/21/2017"
output: html_document

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

### Somatic Variants in SINET 

The VARSCAN pipeline was largely adapted from the  

This section merged together the files from the 

```{r dataparsing, message=FALSE, warning=FALSE, eval =FALSE}

library(tidyverse)
library(stringr)
library(Biostrings)
library(GenomicRanges)
library(VariantAnnotation)

PATIENTVARSOM <- list.files(pattern="_T.snp.Somatic.somaticFilter") %>% 
  sapply(read_tsv, simplify=FALSE) %>%
  bind_rows(.id = "id") %>%
  mutate(id = str_replace(id, "_T.snp.Somatic.somaticFilter", "")) %>%
  mutate(normal_var_freq = str_replace(normal_var_freq, "%", ""), 
         tumor_var_freq= str_replace(tumor_var_freq, "%", "")) %>%
  mutate(normal_var_freq = as.numeric(normal_var_freq), 
         tumor_var_freq = as.numeric(tumor_var_freq))

PATIENTVARSOM.GR<- GRanges(seqnames = Rle(PATIENTVARSOM$chrom),
                            ranges = IRanges(PATIENTVARSOM$position, width=1))

mcols(PATIENTVARSOM.GR)$REF <- DNAStringSet(PATIENTVARSOM$ref)
mcols(PATIENTVARSOM.GR)$ALT <- DNAStringSetList(as.list(PATIENTVARSOM$var))
mcols(PATIENTVARSOM.GR)$PATIENT <- PATIENTVARSOM$id

library(TxDb.Hsapiens.UCSC.hg38.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
library(org.Hs.eg.db)
e2s = toTable(org.Hs.egSYMBOL) 

PATIENTVARSOM.ANNO <- locateVariants(PATIENTVARSOM.GR, txdb, CodingVariants()) %>%
  unique() %>%
  as.data.frame() %>%
  as.tbl()
  
PATIENTVARSOM <-  PATIENTVARSOM.ANNO %>% 
  dplyr::select(chrom = seqnames, position = start, EntrezID = GENEID, Variant_Type = LOCATION, Variant_Location = LOCSTART) %>%
  right_join(PATIENTVARSOM) %>%
  mutate(Symbol = e2s$symbol[match(EntrezID, e2s$gene_id)])

REGIONVARSOM<- list.files(pattern="R..T.snp.Somatic.somaticFilter") %>% 
  sapply(read_tsv, simplify=FALSE) %>%
  bind_rows(.id = "id") %>%
  mutate(id = str_replace(id, ".snp.Somatic.somaticFilter", "")) %>%
  separate(id, into = c("patient_id", "region_id"), sep ="_") %>%
  mutate(normal_var_freq= str_replace(normal_var_freq, "%", ""), 
         tumor_var_freq= str_replace(tumor_var_freq, "%", "")) %>%
  mutate(normal_var_freq = as.numeric(normal_var_freq), 
         tumor_var_freq = as.numeric(tumor_var_freq))
         
REGIONVARSOM.GR<- GRanges(seqnames = Rle(REGIONVARSOM$chrom),
                            ranges = IRanges(REGIONVARSOM$position, width=1))

mcols(REGIONVARSOM.GR)$REF <- DNAStringSet(REGIONVARSOM$ref)
mcols(REGIONVARSOM.GR)$ALT <- DNAStringSetList(as.list(REGIONVARSOM$var))
mcols(REGIONVARSOM.GR)$PATIENT <- REGIONVARSOM$patient_id
mcols(REGIONVARSOM.GR)$REGION <- REGIONVARSOM$region_id

REGIONVARSOM.ANNO <- locateVariants(REGIONVARSOM.GR, txdb, CodingVariants()) %>%
  unique() %>%
  as.data.frame() %>%
  as.tbl()
  

REGIONVARSOM <- REGIONVARSOM.ANNO %>% 
  dplyr::select(chrom = seqnames, position = start, EntrezID = GENEID, Variant_Type = LOCATION, Variant_Location = LOCSTART) %>%
  right_join(REGIONVARSOM) %>%
  mutate(Symbol = e2s$symbol[match(EntrezID, e2s$gene_id)])

write_tsv(REGIONVARSOM, "Region.Somatic.snp.tsv")
write_tsv(PATIENTVARSOM, "Patient.Somatic.snp.tsv")
rm(txdb,e2s, PATIENTVARSOM.GR, REGIONVARSOM.GR, REGIONVARSOM.ANNO, PATIENTVARSOM.ANNO)
```


```{r dataload, message=FALSE, warning=FALSE}
library(tidyverse)
REGIONVARSOM <- read_tsv("Region.Somatic.snp.tsv")
PATIENTVARSOM <- read_tsv("Patient.Somatic.snp.tsv")

```

Plot the Variant frequency vs the Read Depth.

```{r plotVarFrqDepth, message =FALSE, warning= FALSE}

library(ggplot2)
theme_set(theme_bw())

gg<- ggplot(REGIONVARSOM, aes(x = tumor_var_freq, y= tumor_reads1 + tumor_reads2, colour = patient_id)) +
  geom_point() +
  ylab("Tumour Depth") +
  xlab("Tumour Variant Frequency") +
  geom_hline(aes(yintercept=30), color="black", linetype="dashed") 


REGIONVARSOM %>% dplyr::select(1:11, 14:15, Symbol, tumor_var_freq) %>% arrange(desc(tumor_var_freq)) %>% filter(tumor_reads2 > 13)
 
REGIONVARSOM %>% dplyr::select(1:11, 14:15, Symbol, tumor_var_freq) %>% arrange(desc(tumor_var_freq)) %>% filter(Symbol =="CDKN1B")

NREGIONS<- REGIONVARSOM %>% select(patient_id, region_id) %>% unique() %>% group_by(patient_id) %>% summarise(Nregions= n())

REGIONVARSOM <- inner_join(REGIONVARSOM, NREGIONS)


REGIONVARSOM  %>% filter(tumor_reads2 > 16, !is.na(Symbol)) %>% group_by(patient_id, position) %>% mutate(N=n()) %>% select(Symbol, N, Nregions) %>% unique() %>%
  ggplot(aes(reorder(Symbol,-N), N)) +
  geom_bar(stat = "identity") + 
  geom_point(aes(reorder(Symbol,-N), Nregions)) +
  theme(axis.text.x=element_text(angle=45, hjust=1)) 

 
REGIONVARSOM  %>% filter(tumor_reads2 > 16) %>%   group_by(patient_id) %>% summarise(N_mutations = n()) %>%
  ggplot(aes(reorder(patient_id,-N_mutations), N_mutations)) +
  geom_bar(stat = "identity")



```

